print('{0} Desafio 06 {0}'.format('=' * 10))
number = int(input('Digite um número: '))
print('O dobro de {} é: {}'.format(number, number * 2))
print('O triplo de {} é: {}'.format(number, number * 3))
print('A raiz quadrada de {} é: {:.2f}'.format(number, number ** (1/2)))
print('A raiz quadrada de {} é: {:.2f}'.format(number, pow(number, (1/2))))
